
classDiagram
    class Image {
        -id: int
        -filename: str
        -filepath: str
        +upload(image_file: FileStorage)
        +get_predictions() list
    }
    class Prediction {
        -id: int
        -image_id: int
        -label: str
        -confidence: float
        +__init__(image_id: int, label: str, confidence: float)
    }
    Image --> Prediction
