
class Ticket:
    def __init__(self, id, title, description, status):
        self.id = id
        self.title = title
        self.description = description
        self.status = status

class HelpdeskStaff:
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def update_ticket_status(self, ticket_id, new_status):

        pass

class TicketManagementSystem:
    def __init__(self):
        self.tickets = []
        self.helpdesk_staffs = []

    def create_ticket(self, title, description):

        pass

    def update_ticket_status(self, ticket_id, new_status):

        pass

    def get_all_tickets(self):

        return [ticket for ticket in self.tickets if ticket.status == 'open' or ticket.status == 'active']

    def get_helpdesk_staffs(self):

        return self.helpdesk_staffs

    def assign_ticket_to_staff(self, ticket_id, staff_id):

        pass
